# Generated by Django 4.1.7 on 2023-03-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='idn_or_ssn',
            field=models.IntegerField(default=None, help_text='ID card number', max_length=1000),
        ),
    ]
